CREATE TABLE IF NOT EXISTS TASKLIST (
  ID VARCHAR(8) PRIMARY KEY COMMENT 'TASK ID',
  TASK VARCHAR(256) COMMENT 'TASK NAME',
  DEADLINE VARCHAR(10) COMMENT 'DEADLINE YYYY-MM-DD',
  DONE BOOLEAN COMMENT 'DONE TRUE OR FALSE'
);
